[Interface]
PrivateKey = QIJBThDNbg9VgsKYY9Dk4OlbD1/khPZqTXVnrQ4iQX4=
Address = 10.0.0.3/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = f7M27sVkMejGRMhgpc5Gd+yEHOG5pT5qLlt6YdAm2TQ=
PresharedKey = 4bdopHgjcxDHoj4AmAZpo0kpRuNmL8TixqvDHvMWGpA=
Endpoint = 72.56.26.254:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
